version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Rajan@db
      POSTGRES_DB: bikedb
      TZ: Asia/Kolkata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: your-spring-app-image:latest
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      # Overrides application.properties to use the container network
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/postgres

volumes:
  postgres_data: